#!/bin/bash

num=10

usage_exit() {
  echo "midl - output the middle part of the STDIN "
  echo "Usage: $0 [OPTION]"
  echo "
  -n K   output the middle of K lines, instead of the middle 10;

  -h     display this help and exit
  "
  exit 0
}

while getopts hn: OPT
do
  case "$OPT" in
    h) usage_exit
      ;;
    n) num=$OPTARG
      ;;
    *)
       usage_exit; exit 1;
  esac
done

if [ -p /dev/stdin ]; then
  cat - | perl -ane '
    $a[$.]=$_;
    END{
      $b=($. / 2 - ('$num' / 2 )) + 1;
      $e=($. / 2 + ('$num' / 2));
      $b = 1  if $b < 1 ;
      $e = $. if $e > $.;
      for my $i ($b..$e) {
        print $a[$i]
      }
    }
  '
else
  echo "STDIN does not exist" 2> /dev/stdout
  exit 1
fi

exit 0

